const places = ["Makkah", "Madina", "Turkey", "Dubai", "USA"];
console.log(places);
console.log([...places].sort());
console.log(places);
console.log([...places].sort().reverse());
console.log(places);
places.reverse();
console.log(places);
places.reverse();
console.log(places);
places.sort();
console.log(places);
places.sort().reverse();
console.log(places);
